name: APIs testing
on: push
jobs:
  Get-API-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
         command: npm run get-api
      
      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - Get API
          path: cypress/reports/html

  Post-API-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
         command: npm run post-api

      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - Post API
          path: cypress/reports/html

  Put-API-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
         command: npm run put-api

      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - Update API
          path: cypress/reports/html

  Delete-API-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
         command: npm run delete-api

      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
         name: Mochawesome HTML Report - Delete API
         path: cypress/reports/html